### PR TITLE
SQL: partitioning misc fixes [closes #242]

### LINKED ISSUE #242: Partitioning fixes
Fix [review comments](https://github.com/MariaDB/server/commit/7e3093670f32dc156a615c3dda2244f53423cd57) related to partitioning.

Depends on #244 

- [x] comment 1
- [x] comment 2
```diff
--- a/sql/ha_partition.cc
+++ b/sql/ha_partition.cc
@@ -2029,6 +2029,7 @@ int ha_partition::copy_partitions(ulonglong * const copied,
         /* Copy record to new handler */
         (*copied)++;
         if (new_file->ha_external_lock(thd, F_UNLCK) || new_file->ha_external_lock(thd, F_WRLCK))
+        // XXX this looks very fishy. Why are you doing it?
           goto error;
         tmp_disable_binlog(thd); /* Do not replicate the low-level changes. */
         result= new_file->ha_write_row(m_rec0);
```
```diff
--- a/sql/ha_partition.cc
+++ b/sql/ha_partition.cc
@@ -2035,6 +2035,7 @@ int ha_partition::copy_partitions(ulonglong * const copied,
         result= new_file->ha_write_row(m_rec0);
         reenable_binlog(thd);
         if (new_file->ha_external_lock(thd, F_UNLCK) || new_file->ha_external_lock(thd, F_RDLCK) || result)
+        // XXX and here
           goto error;
       }
     }
```

- [x] comment 3
```diff
--- a/sql/ha_partition.h
+++ b/sql/ha_partition.h
@@ -1280,6 +1280,15 @@ class ha_partition :public handler
   virtual bool versioned() const
   {
     return m_innodb;
+    // XXX no, no, no. No engine-specific checks please (I didn't actually
+    // know partitioning does that wtf).
+    // do it like
+    //
+    //   return partition_ht()->flags & HTON_SUPPORTS_SYS_VERSIONING;
+    //
+    // and change the name from "versioned" to something that implies
+    // that the engine supports versioning internally. MyISAM tables can be
+    // versioned too, so "versioned" doesn't equal to "supports sys versioning"
   }
 
   virtual ha_rows part_recs_slow(void *_part_elem)
```

- [x] comment 4
```diff
--- a/sql/partition_element.h
+++ b/sql/partition_element.h
@@ -180,6 +189,10 @@ class partition_element :public Sql_alloc
   };
 
   elem_type type;
+  // XXX I don't think this is needed. 'max_value' flag means
+  // MAXVALUE for RANGE partitioning, DEFAULT for LIST partitioning.
+  // I don't see why it cannot mean AS_OF_NOW for SYSTEM_TIME partitioning.
+  // (in a sense AS_OF_NOW *is* max_value of the second timestamp column)
 
   partition_element()
   : part_max_rows(0), part_min_rows(0), range_value(0),
```

- [x] comment 5
- [x] comment 6
```diff
--- a/sql/partition_element.h
+++ b/sql/partition_element.h
@@ -215,8 +228,12 @@ class partition_element :public Sql_alloc
   part_column_list_val& get_col_val(uint idx)
   {
     DBUG_ASSERT(type != CONVENTIONAL);
+    // XXX I don't see why it should be type != CONVENTIONAL.
+    // The method is fairly generic
     DBUG_ASSERT(list_val_list.elements == 1);
     part_elem_value *ev= static_cast<part_elem_value*>(list_val_list.first_node()->info);
+    // XXX That's not how one uses List.
+    // Better: ev= list_val_list->head();
     DBUG_ASSERT(ev);
     DBUG_ASSERT(ev->col_val_array);
     return ev->col_val_array[idx];
```

- [x] comment 7
- [x] comment 8
```diff
--- a/sql/partition_info.cc
+++ b/sql/partition_info.cc
@@ -889,11 +889,15 @@ partition_info::vers_part_rotate(THD * thd)
 
 bool partition_info::vers_setup_1(THD * thd, uint32 added)
 {
+  // XXX generally, the more cryptic function name is, the longer and more
+  // detailed function comment must be. "vers_setup_1" is very cryptic :)
   DBUG_ASSERT(part_type == VERSIONING_PARTITION);
 
   if (!table->versioned())
   {
     my_error(ER_VERSIONING_REQUIRED, MYF(0), "`BY SYSTEM_TIME` partitioning");
+    // XXX backticks are only used to quote identifiers, don't use them
+    // like this.
     return true;
   }
 ```

- [x] comment 9
```diff
--- a/sql/partition_info.cc
+++ b/sql/partition_info.cc
@@ -910,6 +914,7 @@ bool partition_info::vers_setup_1(THD * thd, uint32 added)
     Field *sys_trx_end= table->vers_end_field();
     part_field_list.empty();
     part_field_list.push_back(const_cast<char *>(sys_trx_end->field_name), thd->mem_root);
+    // XXX what was the content of part_field_list before you repopulated it?
     DBUG_ASSERT(part_field_list.elements == num_columns);
     // needed in handle_list_of_fields()
     sys_trx_end->flags|= GET_FIXED_FIELDS_FLAG;
```

- [x] comment 10
```diff
--- a/sql/partition_info.cc
+++ b/sql/partition_info.cc
@@ -1361,6 +1366,12 @@ bool partition_info::check_engine_mix(handlerton *engine_type,
 */
 
 bool partition_info::check_range_constants(THD *thd, bool init)
+  // XXX what are you trying to do by introducing this 'init' argument?
+  // This function "allocates an array..." and "also check that the
+  // range constants are defined in increasing order".
+  // One could expect init=false to mean that the caller is only
+  // interestd in "check" part, not in "allocate" part. But in the only place
+  // where init=false, you ignore the return value. So, what's the point?
 {
   partition_element* part_def;
   bool first= TRUE;
```

### PR DESCRIPTION
**Pull request by midenok**
Please, review.

### CODE REVIEW

File: sql/partition_info.cc [hunk 1]
```diff
@@ -913,28 +912,56 @@ partition_info::vers_part_rotate(THD * thd)
...
+    if (el->type() == partition_element::AS_OF_NOW)
+    {
+      col_val->max_value= true;
+      col_val->item_expression= NULL;
+      col_val->column_value= NULL;
+      col_val->part_info= this;
+      col_val->fixed= 1;
+      continue;
+    }
+    Item *item_expression= new (thd->mem_root) Item_datetime_literal(thd, &t);
```
Comment (kevgs) [inline sql/partition_info.cc:933]: Maybe check for a failure here?

**Review by kevgs — APPROVED** [review]
