### PR TITLE
SQL: parsing of QUERY FOR [fixes #159]

### LINKED ISSUE #159: `query for system_time` incorrect on INNER JOIN
### Reproduce
```sql
set global default_storage_engine = myisam;
create or replace table t2 (x int) with system versioning;
create or replace table t3 (y int) with system versioning;
insert into t2 values (1), (2), (3);
delete from t2 where x = 3;
insert into t3 values (1);
select * from t2, t3 query for system_time all;
```
### Result
```
+------+------+----------------------------+----------------------------+
| x    | y    | sys_trx_start              | sys_trx_end                |
+------+------+----------------------------+----------------------------+
|    1 |    1 | 2017-03-21 13:26:16.680029 | 2038-01-19 06:14:07.000000 |
|    2 |    1 | 2017-03-21 13:26:16.680029 | 2038-01-19 06:14:07.000000 |
+------+------+----------------------------+----------------------------+
```
### Expected
Same result as in:
```sql
select * from t2 for system_time all, t3 for system_time all;
+------+----------------------------+----------------------------+------+----------------------------+----------------------------+
| x    | sys_trx_start              | sys_trx_end                | y    | sys_trx_start              | sys_trx_end                |
+------+----------------------------+----------------------------+------+----------------------------+----------------------------+
|    1 | 2017-03-17 16:13:10.235132 | 2038-01-19 06:14:07.000000 |    1 | 2017-03-21 13:26:16.680029 | 2038-01-19 06:14:07.000000 |
|    2 | 2017-03-17 16:13:10.235132 | 2038-01-19 06:14:07.000000 |    1 | 2017-03-21 13:26:16.680029 | 2038-01-19 06:14:07.000000 |
|    3 | 2017-03-17 16:13:10.235132 | 2017-03-17 16:13:32.006822 |    1 | 2017-03-21 13:26:16.680029 | 2038-01-19 06:14:07.000000 |
+------+----------------------------+----------------------------+------+----------------------------+----------------------------+
```

### PR DESCRIPTION
**Pull request by kevgs**
Additional test is `main.gis`

### CODE REVIEW

**Comment by midenok** [comment]
Reload trunk.

**Review by midenok — CHANGES_REQUESTED** [review]
Reload trunk.

File: sql/sql_lex.cc [hunk 1]
```diff
@@ -1300,6 +1300,21 @@ int MYSQLlex(YYSTYPE *yylval, THD *thd)
       return FOR_SYM;
     }
     break;
+  case QUERY_SYM:
+  {
+    CHARSET_INFO *cs= thd->charset();
+    const char *p= lip->get_ptr();
+    while (my_isspace(cs, *p))
+      ++p;
+    if (3 < lip->get_end_of_query() - p && 0 == strncasecmp(p, "for", 3) &&
```
Comment (midenok) [inline sql/sql_lex.cc]: More human-friendly: `lip->get_end_of_query() - p > 3`

File: sql/sql_lex.cc [hunk 2]
```diff
@@ -1300,6 +1300,21 @@ int MYSQLlex(YYSTYPE *yylval, THD *thd)
...
+        my_isspace(cs, p[3]))
```
Comment (midenok) [inline sql/sql_lex.cc]: This is check is better before `0 == strncasecmp(p, "for", 3)`.

**Review by midenok — APPROVED** [review]
Minor comments.
