### PR TITLE
SQL: replication fixes [fixes #234]

### LINKED ISSUE #234: Replication fixes
## MyISAM row-based binlog is not working
```sql
-- source include/have_binlog_format_row.inc
-- source include/master-slave.inc
-- source include/have_innodb.inc

connection master;
create or replace table t1 (x int primary key) engine = myisam;
sync_slave_with_master;
alter table t1 with system versioning;

connection master;
insert into t1 values (1);
update t1 set x= 2 where x = 1;
sync_slave_with_master;

connection master;
drop table t1;

-- source include/rpl_end.inc
```

That should work, but instead we have this:
```
Last_SQL_Error	Could not execute Update_rows_v1 event on table test.t1; Can't find record in 't1', Error_code: 1032; handler error HA_ERR_KEY_NOT_FOUND;
``` 

---
## InnoDB should use SBR instead of RBR
InnoDB is not able to work with BRB because there is no sense in transferring trx_ids from one server to another which has a differen trx_id counter. So we need to disable RBR for InnoDB versioning tables completely and use SBR instead. A warning for such cases would be useful.

### PR DESCRIPTION
**Pull request by kevgs**

### CODE REVIEW

File: sql/log_event.h [hunk 1]
```diff
@@ -4588,6 +4588,8 @@ class Rows_log_event : public Log_event
   uchar    *m_extra_row_data;   /* Pointer to extra row data if any */
                                 /* If non null, first byte is length */
 
+  bool m_unversioned_to_versioned;
```
Comment (midenok) [inline sql/log_event.h]: `m_vers_from_plain`

*unversioned* term is wrong, because **un-** means it was versioned once then made non-versioned.

**Review by midenok — APPROVED** [review]
Don't forget to mark all XXX refs as fixed.
