### PR TITLE
Store versioning field flags in a different place (namely EXTRA2)

### LINKED ISSUE #59: Wrong 'WITHOUT SYSTEM VERSIONING' added to 'SHOW CREATE TABLE'
(May be effect of trunk rebasing)

``` diff
--- ./mysql-test/r/ps.result    2016-10-25 05:28:19.354856358 +0000
+++ ./mysql-test/r/ps.reject    2016-10-25 07:56:52.340691138 +0000
@@ -3523,7 +3523,7 @@
 SHOW CREATE TABLE tmp1;
 Table  Create Table
 tmp1   CREATE TEMPORARY TABLE `tmp1` (
-  `c1` decimal(65,38) DEFAULT NULL
+  `c1` decimal(65,38) DEFAULT NULL WITHOUT SYSTEM VERSIONING
 ) ENGINE=MyISAM DEFAULT CHARSET=latin1
 SELECT @a, @a = 123.456789;
 @a     @a = 123.456789
```

### PR DESCRIPTION
**Pull request by kevgs**
Closes #59

### CODE REVIEW

File: sql/table.cc [hunk 1]
```diff
@@ -1808,6 +1818,14 @@ int TABLE_SHARE::init_from_binary_frm_image(THD *thd, bool write,
     reg_field->field_index= i;
     reg_field->comment=comment;
     reg_field->vcol_info= vcol_info;
+    if (extra2_field_flags)
+    {
+      uchar flags= *extra2_field_flags++;
+      if (flags & extra2_field_flags::WITHOUT_SYSTEM_VERSIONING)
```
Comment (midenok) [inline sql/table.cc]: This doesn't build. Also, please rename `WITHOUT_SYSTEM_VERSIONING` to `VERS_OPTIMIZED_UPDATE`, `WITHOUT_SYSTEM_VERSIONING_FLAG` to `VERS_OPTIMIZED_UPDATE_FLAG`.

**Comment by kevgs** [comment]
Second iteration: build fixed, enums renamed.
