### PR TITLE
SQL: prohibit column conversion to system fields for non-empty table [fixes #310]

### LINKED ISSUE #310: Making existing columns be system fields wrong behavior
### Reproduce
```sql
create table t (
a int,
sys_trx_start bigint(20) unsigned,
sys_trx_end bigint(20) unsigned
) engine innodb;
insert into t values (1, 100, 200);
select * from t;
a	sys_trx_start	sys_trx_end
1	100	200
alter table t
change column sys_trx_start sys_trx_start bigint(20) unsigned generated always as row start,
change column sys_trx_end sys_trx_end bigint(20) unsigned generated always as row end,
add period for system_time (sys_trx_start, sys_trx_end),
with system versioning;
select * from t for system_time all;
a	sys_trx_start	sys_trx_end
1	100	200
update t set a=2;
select * from t for system_time all;
a	sys_trx_start	sys_trx_end
1	100	200
```
### Result
Columns became system fields but retained old values (of non-system nature).

### Expected
Such operation should be prohibited when table is not empty.

### PR DESCRIPTION
**Pull request by kevgs**

### CODE REVIEW

File: sql/handler.cc [hunk 1]
```diff
@@ -6950,6 +6951,32 @@ bool Vers_parse_info::check_and_fix_alter(THD *thd, Alter_info *alter_info,
...
+      {
+        if (table->file->info(HA_STATUS_VARIABLE | HA_STATUS_TIME))
+          return true;
+        if (0 < table->file->records())
+        {
+          my_error(ER_VERS_GENERATED_ALWAYS_NOT_EMPTY, MYF(0), f->change.str);
+          return true;
+        }
+        // Table may have strange data if someone will change its data while
+        // we're executing this query.
```
Comment (midenok) [inline sql/handler.cc]: Remove this useless comment.

**Comment by kevgs** [comment]
Notes fixed.
