### PR TITLE
ALTER ADD AUTO_INCREMENT for versioned tables [closes #112]

### LINKED ISSUE #112: AUTO_INCREMENT causes historic data to be updated
# Problem
If a table is altered to add a column with `auto_increment`, then historic data appears to be updated to add a value for this new column. In the test case below, a deleted record is updated.

Since history is idempotent, this is unexpected behavior.

# Solution
This may fall under DDL survival, but history is immutable so this behavior seems to be incorrect.

# Reproduce
```
create table a (cola int(10) primary key) with system versioning;

insert into a values
(1),
(2);

select * from a;
+------+
| cola |
+------+
|    1 |
|    2 |
+------+

delete from a where cola=1;

select * from a;
+------+
| cola |
+------+
|    2 |
+------+

select * from a for system_time all;
+------+
| cola |
+------+
|    1 |
|    2 |
+------+

alter table a
  add colb int(10) auto_increment unique;

select * from a;
+------+------+
| cola | colb |
+------+------+
|    2 |    2 |
+------+------+

select * from a for system_time all;
+------+------+
| cola | colb |
+------+------+
|    1 |    1 |
|    2 |    2 |
+------+------+

```

### PR DESCRIPTION
**Pull request by kevgs**

### CODE REVIEW

File: sql/handler.h [hunk 1]
```diff
@@ -2775,6 +2775,8 @@ class handler :public Sql_alloc
   */
   uint auto_inc_intervals_count;
 
+  ulonglong history_auto_decrement;
```
Comment (midenok) [inline sql/handler.h]: Rename to `vers_auto_decrement`

**Review by midenok — APPROVED** [review]
