### PR TITLE
IB: 0.2 part II

### LINKED ISSUE #8: 0.2 parts I and II: VTQ update
```
DROP TABLE t1;CREATE TABLE t1(x INT UNSIGNED, y INT UNSIGNED, Sys_start TIMESTAMP(6) GENERATED ALWAYS AS ROW START, Sys_end TIMESTAMP(6) GENERATED ALWAYS AS ROW END, PERIOD FOR SYSTEM_TIME (Sys_start, Sys_end)) WITH SYSTEM VERSIONING ENGINE InnoDB;
```
#### Single-statement transaction

```
INSERT INTO t1(x, y) VALUES(8001, 9001);
```

```
#0  mtr_commit (mtr=0x7fa9d9bc4530) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/mtr/mtr0mtr.cc:315
#1  0x0000000000c526a4 in trx_commit_low (trx=0x7fa9b0101678, mtr=0x7fa9d9bc4530) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/trx/trx0trx.cc:1645
#2  0x0000000000c5275d in trx_commit (trx=0x7fa9b0101678) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/trx/trx0trx.cc:1673
#3  0x0000000000c5312a in trx_commit_for_mysql (trx=0x7fa9b0101678) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/trx/trx0trx.cc:1937
#4  0x0000000000aac1d4 in innobase_commit_low (trx=0x7fa9b0101678) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/handler/ha_innodb.cc:4342
#5  0x0000000000aac4d2 in innobase_commit_ordered_2 (trx=0x7fa9b0101678, thd=0x7fa9b0016070) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/handler/ha_innodb.cc:4486
#6  0x0000000000aac8dc in innobase_commit (hton=0x7fa9d6c5a870, thd=0x7fa9b0016070, commit_trx=0x0) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/handler/ha_innodb.cc:4623
#7  0x00000000008e7097 in commit_one_phase_2 (thd=0x7fa9b0016070, all=0x0, trans=0x7fa9b00191d0, is_real_trans=0x1) at /home/midenok/src/mariadb/hagrid/src/sql/handler.cc:1552
#8  0x00000000008e6f93 in ha_commit_one_phase (thd=0x7fa9b0016070, all=0x0) at /home/midenok/src/mariadb/hagrid/src/sql/handler.cc:1533
#9  0x00000000008e686d in ha_commit_trans (thd=0x7fa9b0016070, all=0x0) at /home/midenok/src/mariadb/hagrid/src/sql/handler.cc:1400
#10 0x00000000007e24e8 in trans_commit_stmt (thd=0x7fa9b0016070) at /home/midenok/src/mariadb/hagrid/src/sql/transaction.cc:434
#11 0x000000000069ad86 in mysql_execute_command (thd=0x7fa9b0016070) at /home/midenok/src/mariadb/hagrid/src/sql/sql_parse.cc:6135
#12 0x000000000069f205 in mysql_parse (thd=0x7fa9b0016070, rawbuf=0x7fa9b005e088 "INSERT INTO t1(x, y) VALUES(8001, 9001)", length=0x27, parser_state=0x7fa9d9bc5f70, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/hagrid/src/sql/sql_parse.cc:7789
```
#### Multi-statement transaction

```
start transaction; INSERT INTO t1(x, y) VALUES(8001, 9001); commit;
```

```
#0  mtr_commit (mtr=0x7fa9d9bc4530) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/mtr/mtr0mtr.cc:315
#1  0x0000000000c526a4 in trx_commit_low (trx=0x7fa9b0101678, mtr=0x7fa9d9bc4530) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/trx/trx0trx.cc:1645
#2  0x0000000000c5275d in trx_commit (trx=0x7fa9b0101678) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/trx/trx0trx.cc:1673
#3  0x0000000000c5312a in trx_commit_for_mysql (trx=0x7fa9b0101678) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/trx/trx0trx.cc:1937
#4  0x0000000000aac1d4 in innobase_commit_low (trx=0x7fa9b0101678) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/handler/ha_innodb.cc:4342
#5  0x0000000000aac4d2 in innobase_commit_ordered_2 (trx=0x7fa9b0101678, thd=0x7fa9b0016070) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/handler/ha_innodb.cc:4486
#6  0x0000000000aac8dc in innobase_commit (hton=0x7fa9d6c5a870, thd=0x7fa9b0016070, commit_trx=0x1) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/handler/ha_innodb.cc:4623
#7  0x00000000008e7097 in commit_one_phase_2 (thd=0x7fa9b0016070, all=0x1, trans=0x7fa9b00191b8, is_real_trans=0x1) at /home/midenok/src/mariadb/hagrid/src/sql/handler.cc:1552
#8  0x00000000008e6f93 in ha_commit_one_phase (thd=0x7fa9b0016070, all=0x1) at /home/midenok/src/mariadb/hagrid/src/sql/handler.cc:1533
#9  0x00000000008e686d in ha_commit_trans (thd=0x7fa9b0016070, all=0x1) at /home/midenok/src/mariadb/hagrid/src/sql/handler.cc:1400
#10 0x00000000007e1c50 in trans_commit (thd=0x7fa9b0016070) at /home/midenok/src/mariadb/hagrid/src/sql/transaction.cc:236
#11 0x000000000069811e in mysql_execute_command (thd=0x7fa9b0016070) at /home/midenok/src/mariadb/hagrid/src/sql/sql_parse.cc:5412
#12 0x000000000069f205 in mysql_parse (thd=0x7fa9b0016070, rawbuf=0x7fa9b005e088 "commit", length=0x6, parser_state=0x7fa9d9bc5f70, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/hagrid/src/sql/sql_parse.cc:7789
```
#### Two-phase transaction

```
xa start 'xyz'; INSERT INTO t1(x, y) VALUES(8001, 9001); xa end 'xyz'; xa prepare 'xyz'; xa commit 'xyz';
```

```
#0  mtr_commit (mtr=0x7fa9d9bc45c0) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/mtr/mtr0mtr.cc:315
#1  0x0000000000c526a4 in trx_commit_low (trx=0x7fa9b0101678, mtr=0x7fa9d9bc45c0) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/trx/trx0trx.cc:1645
#2  0x0000000000c5275d in trx_commit (trx=0x7fa9b0101678) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/trx/trx0trx.cc:1673
#3  0x0000000000c5312a in trx_commit_for_mysql (trx=0x7fa9b0101678) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/trx/trx0trx.cc:1937
#4  0x0000000000aac1d4 in innobase_commit_low (trx=0x7fa9b0101678) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/handler/ha_innodb.cc:4342
#5  0x0000000000aac4d2 in innobase_commit_ordered_2 (trx=0x7fa9b0101678, thd=0x7fa9b0016070) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/handler/ha_innodb.cc:4486
#6  0x0000000000aac8dc in innobase_commit (hton=0x7fa9d6c5a870, thd=0x7fa9b0016070, commit_trx=0x1) at /home/midenok/src/mariadb/hagrid/src/storage/xtradb/handler/ha_innodb.cc:4623
#7  0x00000000008e7097 in commit_one_phase_2 (thd=0x7fa9b0016070, all=0x1, trans=0x7fa9b00191b8, is_real_trans=0x1) at /home/midenok/src/mariadb/hagrid/src/sql/handler.cc:1552
#8  0x00000000008e6f93 in ha_commit_one_phase (thd=0x7fa9b0016070, all=0x1) at /home/midenok/src/mariadb/hagrid/src/sql/handler.cc:1533
#9  0x00000000007e38a4 in trans_xa_commit (thd=0x7fa9b0016070) at /home/midenok/src/mariadb/hagrid/src/sql/transaction.cc:895
#10 0x0000000000699f20 in mysql_execute_command (thd=0x7fa9b0016070) at /home/midenok/src/mariadb/hagrid/src/sql/sql_parse.cc:5951
#11 0x000000000069f205 in mysql_parse (thd=0x7fa9b0016070, rawbuf=0x7fa9b005e088 "xa commit 'xyz'", length=0xf, parser_state=0x7fa9d9bc5f70, is_com_multi=0x0, is_next_command=0x0) at /home/midenok/src/mariadb/hagrid/src/sql/sql_parse.cc:7789
```

### LINKED ISSUE #25: Assertion failure on test 'insert'
Appeared in https://github.com/natsys/mariadb_10.2/commit/2d5f222cf5a0ccde1da5ad81fc7ed4325d32f764

[This fails](https://github.com/natsys/mariadb_10.2/blob/2d5f222cf5a0ccde1da5ad81fc7ed4325d32f764/storage/innobase/dict/dict0dict.cc#L2818)

```
(gdb) p size
$1 = 2264
(gdb) p dict_sys->size
$2 = 415

#0  __pthread_kill (threadid=<optimized out>, signo=6) at ../sysdeps/unix/sysv/linux/pthread_kill.c:62
#1  0x00005596ceb06bd7 in my_write_core (sig=6) at /home/kevg/Desktop/mariadb_10.2/mysys/stacktrace.c:456
#2  0x00005596ce4c82e3 in handle_fatal_signal (sig=6) at /home/kevg/Desktop/mariadb_10.2/sql/signal_handler.cc:272
#3  <signal handler called>
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#5  0x00007f8edbf613ea in __GI_abort () at abort.c:89
#6  0x00005596ce8acd31 in dict_index_remove_from_cache_low (table=0x5596d512de78, index=0x5596d512e5f8, lru_evict=0) at /home/kevg/Desktop/mariadb_10.2/storage/innobase/dict/dict0dict.cc:2818
#7  0x00005596ce8ab6b4 in dict_table_remove_from_cache_low (table=0x5596d512de78, lru_evict=0) at /home/kevg/Desktop/mariadb_10.2/storage/innobase/dict/dict0dict.cc:2132
#8  0x00005596ce8abc72 in dict_table_remove_from_cache (table=0x5596d512de78) at /home/kevg/Desktop/mariadb_10.2/storage/innobase/dict/dict0dict.cc:2199
#9  0x00005596ce8b61c0 in dict_close () at /home/kevg/Desktop/mariadb_10.2/storage/innobase/dict/dict0dict.cc:6912
#10 0x00005596ce7e6fc4 in innobase_shutdown_for_mysql () at /home/kevg/Desktop/mariadb_10.2/storage/innobase/srv/srv0start.cc:3239
#11 0x00005596ce6888af in innobase_end (hton=0x5596d506cdf0, type=HA_PANIC_CLOSE) at /home/kevg/Desktop/mariadb_10.2/storage/innobase/handler/ha_innodb.cc:4001
#12 0x00005596ce4c9c7a in ha_finalize_handlerton (plugin=0x5596d4e0d8e8) at /home/kevg/Desktop/mariadb_10.2/sql/handler.cc:449
#13 0x00005596ce29d1bc in plugin_deinitialize (plugin=0x5596d4e0d8e8, ref_check=true) at /home/kevg/Desktop/mariadb_10.2/sql/sql_plugin.cc:1209
#14 0x00005596ce29d625 in reap_plugins () at /home/kevg/Desktop/mariadb_10.2/sql/sql_plugin.cc:1287
#15 0x00005596ce29f4a8 in plugin_shutdown () at /home/kevg/Desktop/mariadb_10.2/sql/sql_plugin.cc:1945
#16 0x00005596ce1b55ce in clean_up (print_message=true) at /home/kevg/Desktop/mariadb_10.2/sql/mysqld.cc:2189
#17 0x00005596ce1b517b in unireg_end () at /home/kevg/Desktop/mariadb_10.2/sql/mysqld.cc:2068
#18 0x00005596ce1b508f in kill_server (sig_ptr=0x0) at /home/kevg/Desktop/mariadb_10.2/sql/mysqld.cc:1995
#19 0x00005596ce1b50b7 in kill_server_thread (arg=0x7f8ede9fc5d0) at /home/kevg/Desktop/mariadb_10.2/sql/mysqld.cc:2018
#20 0x00005596ceaafd91 in pfs_spawn_thread (arg=0x5596d6288370) at /home/kevg/Desktop/mariadb_10.2/storage/perfschema/pfs.cc:1862
#21 0x00007f8edc98970a in start_thread (arg=0x7f8ede968f00) at pthread_create.c:333
#22 0x00007f8edc0320ff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```

Looks like dict_sys->size needs to be incremented in some places where heap allocations occur.

### PR DESCRIPTION
**Pull request by midenok**
- moved vers_notify_vtq() to commit phase;
- low_level insert (load test passed);
- rest of SYS_VTQ columns filled: COMMIT_TS, CONCURR_TRX;
- savepoints support;
- I_S.INNODB_SYS_VTQ adjustments:
  - limit to I_S_SYS_VTQ_LIMIT(10000) of most recent records;
  - CONCURR_TRX limit to I_S_MAX_CONCURR_TRX(100) with '...' truncation marker;
  - TIMESTAMP fields show fractions of seconds.

Resolves #8, fixes #25

### CODE REVIEW

**Comment by midenok** [comment]
Please, review.

File: storage/innobase/btr/btr0pcur.cc [hunk 1]
```diff
@@ -442,6 +442,58 @@ btr_pcur_move_to_next_page(
...
+	page_t*		next_page;
+
+	ut_ad(cursor->pos_state == BTR_PCUR_IS_POSITIONED);
+	ut_ad(cursor->latch_mode != BTR_NO_LATCHES);
+	ut_ad(btr_pcur_is_before_first_on_page(cursor));
+
+	cursor->old_stored = BTR_PCUR_OLD_NOT_STORED;
+
+	page = btr_pcur_get_page(cursor);
+	next_page_no = btr_page_get_prev(page, mtr);
```
Comment (kevgs) [inline storage/innobase/btr/btr0pcur.cc]: Assigning 'prev' to 'next_page' looks confusing.

File: storage/innobase/include/btr0pcur.h [hunk 2]
```diff
@@ -340,6 +351,18 @@ btr_pcur_move_to_next_page(
 				last record of the current page */
 	mtr_t*		mtr);	/*!< in: mtr */
 /*********************************************************//**
+Moves the persistent cursor to the previous record on the next page.
```
Comment (kevgs) [inline storage/innobase/include/btr0pcur.h]: Comments on declaration and definition of a function differs.

File: storage/innobase/dict/dict0load.cc [hunk 3]
```diff
@@ -754,36 +769,58 @@ ullong*		col_concurr_trx)
...
+		concurr_n = I_S_MAX_CONCURR_TRX;
+		truncated = true;
 	}
-	*col_concurr_trx = mach_read_from_8(field);
 
+	if (concurr_n == 0) {
+		*col_concurr_trx = NULL;
+		return(NULL);
+	}
+	*col_concurr_trx = static_cast<char*>(mem_heap_alloc(heap, concurr_n * (TRX_ID_MAX_LEN + 1) + 3 + 1));
```
Comment (kevgs) [inline storage/innobase/dict/dict0load.cc:813]: This is probably affected by https://github.com/natsys/mariadb_10.2/issues/25

File: storage/innobase/dict/dict0load.cc [hunk 4]
```diff
@@ -754,36 +769,58 @@ ullong*		col_concurr_trx)
 	if (rec_get_n_fields_old(rec) != DICT_NUM_FIELDS__SYS_VTQ) {
 		return("wrong number of columns in SYS_VTQ record");
 	}
-
+	/////////////
```
Comment (krizhanovsky) [inline storage/innobase/dict/dict0load.cc]: The comments looks like a garbage

File: storage/innobase/dict/dict0load.cc (hunk 3 above)
Comment (midenok) [reply storage/innobase/dict/dict0load.cc:813]: No, it only counts system table's and their indexes heaps.

File: storage/innobase/btr/btr0pcur.cc (hunk 1 above)
Comment (midenok) [reply storage/innobase/btr/btr0pcur.cc]: I'm glad you noticed. Fixed.

File: storage/innobase/include/btr0pcur.h (hunk 2 above)
Comment (midenok) [reply storage/innobase/include/btr0pcur.h]: Fixed.

File: storage/innobase/dict/dict0load.cc (hunk 4 above)
Comment (midenok) [reply storage/innobase/dict/dict0load.cc]: Fixed

File: storage/innobase/row/row0ins.cc [hunk 5]
```diff
@@ -3391,63 +3409,134 @@ row_ins_step(
...
+		/* The row had already been copied to the table. */
+		fprintf(stderr, "InnoDB: duplicate VTQ record!\n");
+		return DB_SUCCESS;
+	default:
+		return err;
+	}
+
+	mem_heap_t* offsets_heap = mem_heap_create(1024);
+
+	do {
```
Comment (kevgs) [inline storage/innobase/row/row0ins.cc:3460]: Late review.

We know exact VTQ table schema. And we know it has exactly 2 secondary index. Thus this loop should iterate exactly 2 times. And we expect DB_SUCCESS, otherwise it's fine to die in assert.

File: storage/innobase/row/row0ins.cc [hunk 6]
```diff
@@ -3391,63 +3409,134 @@ row_ins_step(
...
+		n_index++;
 
-	dtuple_t* row = dtuple_create(heap, dict_table_get_n_cols(sys_vtq));
-	dict_table_copy_types(row, sys_vtq);
+		if (!(index = dict_table_get_next_index(index))) {
+			break;
+		}
+
+		if (index->type & DICT_FTS) {
```
Comment (kevgs) [inline storage/innobase/row/row0ins.cc:3467]: VTQ table has no fulltext indexes. This condition is always false.

File: storage/innobase/row/row0ins.cc (hunk 5 above)
Comment (midenok) [reply storage/innobase/row/row0ins.cc:3460]: Made assert on 2 times. It's not fine to die on index errors.

File: storage/innobase/row/row0ins.cc (hunk 6 above)
Comment (midenok) [reply storage/innobase/row/row0ins.cc:3467]: Fixed.
